In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [17]:
data = pd.read_csv('Resources/booking.csv') 
data.head()

,Booking_ID,number of adults,number of children,number of weekend nights,number of week nights,type of meal,car parking space,room type,lead time,market segment type,repeated,P-C,P-not-C,average price,special requests,date of reservation,booking status
0,INN00001,1,1,2,5,Meal Plan 1,0,Room_Type 1,224,Offline,0,0,0,88.00,0,10/2/2015,Not_Canceled
1,INN00002,1,0,1,3,Not Selected,0,Room_Type 1,5,Online,0,0,0,106.68,1,11/6/2018,Not_Canceled
2,INN00003,2,1,1,3,Meal Plan 1,0,Room_Type 1,1,Online,0,0,0,50.00,0,2/28/2018,Canceled
3,INN00004,1,0,0,2,Meal Plan 1,0,Room_Type 1,211,Online,0,0,0,100.00,1,5/20/2017,Canceled
4,INN00005,1,0,1,2,Not Selected,0,Room_Type 1,48,Online,0,0,0,77.00,0,4/11/2018,Canceled

In [18]:
data.fillna(method='ffill', inplace=True)

In [19]:
# Convert categorical variables to numerical using one-hot encoding
data = pd.get_dummies(data, columns=['type of meal', 'room type', 'market segment type', 'booking status'])

In [20]:
# Drop non-numeric columns or columns with unique identifiers
data.drop(['Booking_ID', 'date of reservation'], axis=1, inplace=True)

In [22]:
data.head()

,number of adults,number of children,number of weekend nights,number of week nights,car parking space,lead time,repeated,P-C,P-not-C,average price,...,room type_Room_Type 5,room type_Room_Type 6,room type_Room_Type 7,market segment type_Aviation,market segment type_Complementary,market segment type_Corporate,market segment type_Offline,market segment type_Online,booking status_Canceled,booking status_Not_Canceled
0,1,1,2,5,0,224,0,0,0,88.00,...,False,False,False,False,False,False,True,False,False,True
1,1,0,1,3,0,5,0,0,0,106.68,...,False,False,False,False,False,False,False,True,False,True
2,2,1,1,3,0,1,0,0,0,50.00,...,False,False,False,False,False,False,False,True,True,False
3,1,0,0,2,0,211,0,0,0,100.00,...,False,False,False,False,False,False,False,True,True,False
4,1,0,1,2,0,48,0,0,0,77.00,...,False,False,False,False,False,False,False,True,True,False

In [21]:
# Split the dataset into features (X) and target variable (y)
X = data.drop('booking status', axis=1)  # Features
y = data['booking status']  # Target variable

KeyError: "['booking status'] not found in axis"

In [ ]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Step 2 & 3: Model Selection and Training
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

In [ ]:
# Train the Random Forest classifier
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
# Predict on the test set
y_pred = rf_classifier.predict(X_test)
print(y_pred)

[0 0 0 ... 0 0 0]

In [ ]:
# Generate classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7189
           1       0.86      0.75      0.80        40
           2       0.20      0.17      0.18         6
           3       0.67      0.60      0.63        10
           4       0.67      0.67      0.67         3
           5       0.00      0.00      0.00         0
           6       0.00      0.00      0.00         1
          11       1.00      0.71      0.83         7
          13       1.00      1.00      1.00         1

    accuracy                           1.00      7257
   macro avg       0.60      0.54      0.57      7257
weighted avg       1.00      1.00      1.00      7257

c:\Users\kryst\anaconda_3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\kryst\anaconda_3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\kryst\anaconda_3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\kryst\anaconda_3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\kryst\anaconda_3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\kryst\anaconda_3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))